스토어페이지, 라이브러리페이지 수정
WakGames/Waktaverse-Games pull request #118
Opened 2023-04-16 03:03 UTC by lmotp

## 개요

- 스토어페이지, 라이브러리페이지 수정

## 작업 내용

- 스토어페이지 카테고리 변경 시 오류 수정
- 라이브러리 페이지 필터 os 선택 시 아이템없으면 noneItem 나오게끔 수정
- 해당 페이지에 리스트 없으면 페이지네이션 줄어들게 수정
- 라이브러리 제거 했을 때 필터태그 해당 값 없으면 삭제 되게끔 수정

## 스크린샷(or 동영상)

## 기타(특이 사항)

- 테스트를 완벽하게 아니어서 문제 있으면 말씀주세요.

2023-04-16 08:03 UTC, markyul reviewed
일단 제가 테스트 하면서 나온거네요!

2023-04-16 08:03 UTC, markyul commented on frontend/src/components/Library/LibraryView/index.js
>      return <LibraryViewSkeleton count={count} />;
라이브러리 페이지 들어가면 key 관련 에러가 찍히는데(보는데는 문제없습니다), 이 컴포넌트 안에서 찍히는 에러 같습니다.

2023-04-18 02:40 UTC, DOS0313 commented
게임 세부정보 페이지에 해당하는 경우이긴한데
로그인이 안되있는 상태에서 다운로드 버튼 클릭 시 로그인 모달이 뜹니다
(특별한 이유가 없다면 수정 해주실 수 있을까요?)

2023-04-22 14:14 UTC, DOS0313 requested changes
![image](https://user-images.githubusercontent.com/119480595/233789963-f9549341-e155-4a19-b816-812e786b2b88.png)
해당 문제가 추가적으로 패치되지 않은 것 같은데 기록만 안되어 있는걸까요?

2023-04-29 02:36 UTC, DOS0313 commented
추가적으로 편의성을 위한 패치 하나 부탁 드리겠습니다
스토어 페이지(/store)에서 게임 확인 후 다시 돌아왔을 때 스크롤은 보존되지만 페이지네이션의 첫 번째 페이지로 이동하는데
수정 가능할까요?

2023-05-05 07:09 UTC, DOS0313 commented
혹시 게임플레이 영상 페이지에서 정렬 기준이 페이지가 바뀌었을 때 초기화 되는 현상 해결 됬을까요?

2023-05-10 13:21 UTC, Kim-EunKyu commented
팀장님이 주신 피드백 다른 pr에서 수정하여 이어가겠습니다

2023-05-10 13:21 UTC, merged