Introduction 메인 페이지
WakGames/Waktaverse-Games pull request #150
Opened 2023-06-02 11:01 UTC by Se0nAh

## 개요

- intro Header 및 SideNav css 변경
- /intro 페이지 작업

## 작업 내용

- Header height에 맞춰 padding도 반응형으로 수정
- page 내 z-index 1이상으로 높일시 SideNav를 가리게 되어 SideNav에도 z-index 추가
- Intro 페이지 애니메이션 제외하고 작업 (라이브러리 도입 생각중입니다)

## 스크린샷(or 동영상)

https://github.com/WakGames/Waktaverse-Games/assets/49391145/1c8736c5-3deb-48d8-a4b7-658602e55d1b

## 기타(특이 사항)

-

2023-06-02 11:44 UTC, markyul reviewed
Main 폴더 안에 components 폴더를 없애는건 어떨까요?
components 폴더 안에 있는 컴포넌트는 재사용되는 경우만 넣어주는거죠

2023-06-02 14:19 UTC, Se0nAh commented
@markyul  components 지우고 Banner랑 ContentSection을 Main 바로 하위에 위치시키자는 말씀이시죠?

2023-06-02 15:32 UTC, DOS0313 requested changes
Figma 디자인이 제대로 반영되지 않은 부분이 있는 것 같습니다.
- Header 부분 색상 변경 
(#121212 -> #000000) (@markyul 님이 작업 하신거긴 합니다) (개발자 포탈 작업 시 Header랑 구분이 안될거 같아서)
- Footer 부분도 작업 해주셔야 할 듯합니다
- '지금 바로 Waktaverse Games Store로 이동하기' 부분 화살표 변경이 필요할듯 합니다
(필요 시 제공 해드리겠습니다)

2023-06-03 11:51 UTC, Se0nAh commented
@DOS0313 
- footer는 새 pr 로 작업해서 올리겠습니다
- 기존 코드 참고하니 아이콘은 fontawsome 라이브러리 이용하시는 것 같아서 거기서 비슷한 걸로 찾아 적용했는데 생긴 게 좀 차이가 나긴 하죠 ㅎㅎ; 피그마에 맞춰서 수정하겠습니다
- desktop기준 배너 크기 말씀이실까요? 현재 height 850px 고정이고 width는 브라우저 사이즈 맞춰서 늘어나게 되어있는데 어떤 부분을 수정하면 좋을지  요구사항 좀 더 적어주심 감사하겠습니다!

2023-06-03 12:03 UTC, DOS0313 commented
Figma에서는 Flow 실행 시 아래에 여백이 남아 스크롤 가능성을 보여주고 있는데
웹사이트에서는 위의 URL 입력칸, 즐겨찾기 등 때문에 화면 전체가 차게 보여지는거 같아
![image](https://github.com/WakGames/Waktaverse-Games/assets/119480595/9c7f8962-fe51-4e9b-806f-35f0c296f1a0)
위 이미지 처럼 대략 **60px 정도 여백**이 있으면 좋을거 같아 말씀드렸습니다

(자르실 경우 배너 하단 그냥 60px 자르셔도 문제 없을 듯합니다)

2023-06-03 17:33 UTC, Se0nAh commented
@DOS0313 @markyul 수정 요청하신 부분 반영했습니다! 
배너 부분은 혹시 몰라 80px 정도 줄였는데(770px) 어떨지 모르겠네요 한 번 확인해주시고 편하게 의견 주세용

2023-06-04 03:21 UTC, DOS0313 approved these changes
Footer 랑 애니메이션은 새 PR로 작업해주시는 걸로 하셨으니

일단 디자인 반영 쪽에는 크게 문제는 없는거 같습니다!

2023-06-06 08:48 UTC, merged