Feature: 개발자 포탈 UI만
WakGames/Waktaverse-Games pull request #193
Opened 2023-06-23 11:24 UTC by markyul

## 개요

- 개발자 포탈 UI만 작업

## 작업 내용

- 로그인 여부에 따른 페이지 분리(로그인 작업 x)

개발자인 경우
- tab으로 페이지 이동
- figma에 따라 UI 작업

## 스크린샷(or 동영상)
### 로그인 안하거나 개발자가 아닌 경우

https://github.com/WakGames/Waktaverse-Games/assets/52916848/cf52321d-34ee-4ead-9103-bfb75102dfb4

### 개발자인 경우

https://github.com/WakGames/Waktaverse-Games/assets/52916848/5217b55c-14b7-4399-99be-5c10ca7a7cc4

### 알림 발송 Tab

https://github.com/WakGames/Waktaverse-Games/assets/52916848/0d8d4a48-9410-4fe8-bb76-0850fa10552d

### 게임 연동

1. 게임 목록 -> 정보

https://github.com/WakGames/Waktaverse-Games/assets/52916848/65f7cf02-c3c0-4f96-b0e5-ba4a7637ec60

2. 게임 정보 -> 설명 수정

https://github.com/WakGames/Waktaverse-Games/assets/52916848/d9679a5e-9bb7-4927-af1c-60544811ed0b

3. 게임 정보 -> 이미지 수정

https://github.com/WakGames/Waktaverse-Games/assets/52916848/0f2baf73-3da5-49cc-8aa0-fbf70ab0e6e4
* 지금은 맥북 화면이라 width 1680px 이상일 때는 안보이네요

4. 게임 정보 -> 도전과제 수정

https://github.com/WakGames/Waktaverse-Games/assets/52916848/83a3205a-9ee3-4082-9c31-86d99676467d

## 기타(특이 사항)

- api 관련 기능은 하지 않았지만 너무 많이 코드를 추가해서 UI 만 PR 합니다.
- 수정할 부분 있다면 말해주세요

2023-06-23 15:23 UTC, DOS0313 commented
frontend 브랜치에서 Footer까지 받아와서 적용해주실 수 있을까요?

2023-06-24 12:10 UTC, DOS0313 requested changes
**정말 수고하셨습니다!**

한 가지 간단한 수정 필요해 보이네요!
- 마크다운 에디터 height 수정 
(Desktop/Tablet : 530px / Mobile : 328px)

그리고 혹시 들어간 요소가 몇 개 없는 페이지의 경우 여백이 생기는데 Footer 적용하시면서 작업 하실 예정일까요?

2023-06-25 10:07 UTC, Se0nAh approved these changes
수고하셨습니다!!

2023-06-25 13:38 UTC, DOS0313 approved these changes
**수고하셨습니다!**
(시트에 페이지 별로 작업 목록 분리해두겠습니다)

2023-06-26 07:14 UTC, merged