프로필 페이지 팬덤 그룹 수정 기능 구현
WakGames/Waktaverse-Games pull request #216
Opened 2023-07-08 13:06 UTC by Kim-EunKyu

## 개요

- 프로필 페이지 팬덤 그룹 수정 기능 추가

## 작업 내용

- 기존 팬덤 그룹 영역에 edit 버튼 추가
- edit하는 모달 추가
- 유저가 선택한 팬덤 그룹 클릭 여부에 따라 팬덤을 보여주도록 api연동

## 스크린샷(or 동영상)
https://github.com/WakGames/Waktaverse-Games/assets/59270535/5bc65ec8-1a01-4e82-8981-a7f6283b2e01
## 기타(특이 사항)

- 제가 테스트 할땐 큰 문제는 없어 보이는데 혹시 이상없는지 테스트해봐주시면 감사하겠습니다.
- 작업하다보니 약간 덩어리(?)부분들은 큰 컴포넌트로 분리하는게 낫겠더라구요.. 감안하고 봐주시면 감사하겠습니다.
- 피드백은 언제나 환영입니다! 이상한 구조나 로직 보이면 말씀주세요 ㅎㅎ

2023-07-08 13:55 UTC, DOS0313 requested changes
**그룹 편집 기능은 정상 작동하네요! 수고하셨습니다!**

혹시, 그룹 8개 이상 등록되나요?
그리고 그룹 기능이라 '아직 선택한 팬덤이 없어요' 말고
'포함되어 있는 그룹이 없습니다' 18px (Regular)로 변경해주세요
(Figma 참고)

(다른 팀원 분들 approve 내려오면 머지 하셔도 됩니다)

**프로필 페이지 추가 작업 필요한 부분**
- 다른 부분도 없을 시 없음 표기
(Figma 참고)
- 프로필 이미지 불러오는 기능 패치는 되어있나요?
(저번에 추가했다고 들은 것 같아서)

2023-07-08 14:04 UTC, Kim-EunKyu commented
@DOS0313 
1. 넵 8개 이상도 가능한 상태이고 실제로 우선 피그마에 있는 개발자도 요소에 들어있긴합니다 (유저 정보 가져오는 api에 있는 isDev로 판단하고있음)
2. 프로필 이미지 불러오는 부분은 되어있긴합니다만, 우선 저 같은 경우에는 profileImg 속성이 null로 와서 확인해보진 못하였습니다. 혹시 테스트가 필요하다면 @NeuroWhAI 님께 같이 확인이 필요할 수 도 있을것같아요. (다시 네이버 id 등록을 해야한다던가..등등)

나머지 피드백 주신 부분 반영해두겠습니다~

2023-07-08 14:16 UTC, DOS0313 commented
> 1. 넵 8개 이상도 가능한 상태이고 실제로 우선 피그마에 있는 개발자도 요소에 들어있긴합니다 (유저 정보 가져오는 api에 있는 isDev로 판단하고있음)

8개 까지만 가능하게 수정해주셔야 할 듯 합니다. 
(제한을 두는게 디자인 상에서 더 보기 좋을 것 같아서요)

2023-07-08 14:42 UTC, NeuroWhAI commented
> @DOS0313
> 
> 1. 넵 8개 이상도 가능한 상태이고 실제로 우선 피그마에 있는 개발자도 요소에 들어있긴합니다 (유저 정보 가져오는 api에 있는 isDev로 판단하고있음)
> 2. 프로필 이미지 불러오는 부분은 되어있긴합니다만, 우선 저 같은 경우에는 profileImg 속성이 null로 와서 확인해보진 못하였습니다. 혹시 테스트가 필요하다면 @NeuroWhAI 님께 같이 확인이 필요할 수 도 있을것같아요. (다시 네이버 id 등록을 해야한다던가..등등)
> 
> 나머지 피드백 주신 부분 반영해두겠습니다~

소셜로그인 처음할 때 필수 정보에 프로필 사진이 없었다가 추가된거라 그 이전에 가입한 계정은 프로필 이미지 정보가 없습니다. 테스트 필요하시면 네이버에서 외부 서비스 동의 철회, DB 삭제하고 다시 가입해보시면 되긴 할텐데 그냥 그 이후에 가입하신 분이나 신규 부계로 테스트 해보시는 게 더 빠를 것 같긴 합니다.

2023-07-08 15:00 UTC, NeuroWhAI requested changes

2023-07-08 15:00 UTC, NeuroWhAI commented on frontend/src/domain/store/components/Profile/profileUtils.js
> +  { img: developer, enFandom: 'developer', fandom: '우왁굳이 너무해', subTitle: '개발팀', isSelected: false },
@DOS0313 프로필의 그룹 목록에 본인이 선택한 팬덤 그룹 + 속한 게임/어플 그룹 다 나오는 걸 의도하신 게 맞으신가요? 그리고 그룹 편집 화면에서도 둘 다 편집 가능한건가요? 그렇다면 게임/어플 그룹을 편집으로 제외하면 그룹에서 실제로 나가는 동작을 수행해야 하나요? 그러니까 사용자가 직접 그룹에서 나갈때 사용되는 기능인가요?

2023-07-08 15:03 UTC, DOS0313 commented on frontend/src/domain/store/components/Profile/profileUtils.js
> +  { img: developer, enFandom: 'developer', fandom: '우왁굳이 너무해', subTitle: '개발팀', isSelected: false },
- 선택한 팬덤 그룹 + 속한 게임/어플 그룹 전부 나오는 것으로 의도한게 맞습니다
- 둘 다 편집 가능합니다
- 프로필 페이지의 표시만 수정이 가능하고 나갈 때는 개발자 포탈을 이용해야 합니다
(프로필 페이지는 진짜 장식용(수집품 전시관?) 입니다)

2023-07-08 16:22 UTC, markyul reviewed
고생하셨어요!

2023-07-09 12:43 UTC, Kim-EunKyu commented on frontend/src/GlobalStyle.js
> +}
@markyul 요게 들어가면 모달 창이 떴을때 뒷 배경에 스크롤 없어지게 하는 역할입니다!

2023-07-09 12:43 UTC, Kim-EunKyu commented on frontend/src/domain/store/components/Profile/Button.js
> +    <Frame isOk={isOk} onClick={onClick}>
@markyul 오 이렇게 하는게 좀 더 타입적인 관점에서 직관적이겠네요 피드백 감사합니다!

2023-07-15 08:31 UTC, DOS0313 requested changes
디스코드로만 말씀을 드려서 그런지 Figma 수정 사항 부분이 누락된 것 같습니다..
(Github로 확실히 전달 드렸어야 했는데..)

개발 편의성을 위해 **그룹, 팬덤으로 분리된 디자인**으로 **변경** 되었습니다
- 그룹은 1개만 표시 가능
- 팬덤은 6개까지만 표시 가능
- 각자 띄우는 모달이 다름

자세한 내용은 Figma 확인 바랍니다
(Frame : Profile, Profile_edit_fandom, Profile_edit_group, Profile - Empty)

**항상 수고해주셔서 감사합니다!**

2023-07-15 08:31 UTC, DOS0313 commented
혹시, 저만 이렇게 표시되는 걸까요?
![image](https://github.com/WakGames/Waktaverse-Games/assets/119480595/9629b1e9-b290-4fd5-8b84-219845f0934e)

2023-07-15 08:34 UTC, Kim-EunKyu commented
@DOS0313 
도전과제 없을때 말씀이시면 hover 직업할때 도전과제 없을때 문구 표시하는거 작업 따로하려고 합니다!

2023-07-15 08:35 UTC, DOS0313 commented
@Kim-EunKyu 
도전과제는 그렇게 해주셔도 되는데 팬덤, 그룹 분리 디자인은 작업이 됐을까요?

2023-07-15 08:38 UTC, Kim-EunKyu commented
@DOS0313 아 그말씀이시군요
그룹 박스 디자인 넣는거까지 진행하고 공유드리겠습니다!

2023-07-15 08:38 UTC, DOS0313 commented
@Kim-EunKyu 
화이팅입니다! 항상 너무 수고해주셔서 감사합니다!

2023-07-22 15:11 UTC, DOS0313 requested changes
팬덤 6개 전부 선택 시 아래 여백이 Figma 디자인과 다른 것 같습니다
![Uploading image.png…]()

2023-07-28 08:15 UTC, merged