feat: store 검색 기능 추가
WakGames/Waktaverse-Games pull request #217
Opened 2023-07-09 02:42 UTC by Se0nAh

## 개요

- store 검색기능이 추가되었습니다
- 결과가 없을 때 보여주는 페이지의 폰트 기울기 스타일 제거
- PageLayout title 을 각 페이지에서 자유롭게 결정하도록 수정

## 작업 내용

- 검색창에 keyword입력 후 엔터 입력시 /store?search={keyword} 로 이동
- game name이 keyword를 포함하고 있는지 체크해서 필터링함

## 스크린샷(or 동영상)
![Jul-09-2023 11-36-10](https://github.com/WakGames/Waktaverse-Games/assets/49391145/c45c84aa-edef-423f-81ca-1cbf76a43246)

2023-07-09 05:17 UTC, DOS0313 requested changes
**버그가 있는 것 같습니다!**
(로딩 문제인가?)

디스코드 확인해주세요!

2023-07-09 07:46 UTC, Se0nAh commented
@DOS0313 알려주신 현상 해결해서 커밋 추가했습니다! 감사합니다
store 페이지 사이드이펙트가 점점 복잡해지는 것 같은데 후에 한 번 정리해야겠네요 ;-;

2023-07-09 10:35 UTC, markyul reviewed
수고하셨습니다!

2023-07-10 13:57 UTC, DOS0313 commented
디스코드에 올려놓은 버그 해결 되는대로
바로 머지해주세요

2023-07-10 14:23 UTC, Se0nAh commented
수정했습니다!!
![Jul-10-2023 23-22-47](https://github.com/WakGames/Waktaverse-Games/assets/49391145/190d9f50-4b0b-420a-b2f2-d760a8438d45)

2023-07-10 14:24 UTC, merged