게임 상세 페이지 - [플레이 영상 겹침, 하단 마진]
WakGames/Waktaverse-Games pull request #254
Opened 2023-07-29 14:43 UTC by Kim-EunKyu

## 개요

- 게임 상세 페이지 이슈 수정
- https://github.com/WakGames/Waktaverse-Games/issues/182
- https://github.com/WakGames/Waktaverse-Games/issues/251

## 작업 내용

- 게임 플레이 영상 겹치는 문제 수정
- viewport 사이즈 분기 적용하여 게임 플레이 영상 수 조절
- 게임 상세 페이지 하단 마진 적용
- 게임 플레이 영상에 하이퍼링크 적용

## 스크린샷(or 동영상)

## 기타(특이 사항)

- 플레이 영상 더보기 버튼 관련해서는 store쪽 코드도 한번 봐야할 것 같아서 여기까지 끊고 코드 분석 한 후에 적용해보겠습니다!
- 이상한 부분이나 개선할 부분 보이시면 피드백 부탁드립니다 (__)

2023-07-29 15:22 UTC, DOS0313 requested changes
디자인적으로 수정 필요한 부분이 있어보이네요
- 보고있는 사진 부분과 여백 일치하지 않음
- 게임 플레이 영상 부분 여백이 디자인과 여러가지 부분에서 다름
(스크롤바 떄문에 사이즈 조정한 것은 ㅇㅈ)
![image](https://github.com/WakGames/Waktaverse-Games/assets/119480595/f406af0a-f103-46f6-92d1-f4666a990d68)

2023-07-29 15:42 UTC, markyul approved these changes
수를 조절하셨군요! 잘봤습니다

2023-07-30 06:43 UTC, Kim-EunKyu commented
@DOS0313 
피그마 보면서 폰트사이즈나 말씀해주신 여백 부분이 확실히 다른부분이 있어서 데스크톱 기준으로 수정해보았는데 혹시라도 빠진곳있으면 알려주시면 감사하겠습니다~

2023-07-30 10:46 UTC, DOS0313 approved these changes
**수고하셨습니다!**
오늘 저녁 중으로 머지 진행하겠습니다

2023-07-31 04:02 UTC, merged