feat: 반응형 헤더 오류 수정 및 store 반응형 적용
WakGames/Waktaverse-Games pull request #277
Opened 2023-08-20 03:43 UTC by Se0nAh

## 개요

반응형 헤더 오류 수정 및 store 반응형 적용

## 작업 내용

- 헤더 오류 수정 
  - 좌측 네비게이션 기능 오류 수정
  - 검색 완료후 닫히도록 수정
- 스토어 페이지 반응형 적용 
  - 필터부분은 제외 (flex wrap 정도만 적용)
  - column 개수 조정

## 스크린샷(or 동영상)
![Aug-20-2023 12-34-19](https://github.com/WakGames/Waktaverse-Games/assets/49391145/066036f4-a696-4c7d-b1a2-e2512712b5d7)

2023-08-20 06:52 UTC, DOS0313 approved these changes
기능작동에는 문제가 없습니다

(Figma에서 디자인 수정이 필요할 것 같습니다)
(게임 리스트 페이지 진입 시 메인 화면으로 돌아갈 방법이 없네요;;)

2023-08-20 07:36 UTC, DOS0313 commented
> 기능작동에는 문제가 없습니다
> 
> (Figma에서 디자인 수정이 필요할 것 같습니다) (게임 리스트 페이지 진입 시 메인 화면으로 돌아갈 방법이 없네요;;)

Figma 디자인 수정 진행되었습니다
(헤더에 로고 상시 표기)

2023-08-20 12:16 UTC, DOS0313 commented
해당 PR에 Figma 디자인 변경점 적용 중이실까요?
(다른 브랜치/PR에서 적용하시는가 해서요)

2023-08-20 14:40 UTC, Se0nAh commented
@DOS0313 변경사항 반영 커밋 추가했습니다!

2023-08-20 14:50 UTC, DOS0313 requested changes
수고하셨어요!
근데 수정이 필요한 부분이 꽤 있는 것 같습니다.. (모바일 기기로 실행해보니...)

**수정 필요**
- 메인 페이지(/) 에서 헤더가 같이 내려오지 않습니다
- 메인 페이지(/) 의 헤더 디자인도 바탕이 투명한 상태가 아닌 로고가 표시되는 헤더로 고정입니다
(Figma 확인 바람)
- 모바일 기기에서 스크롤 시 헤더가 가려집니다
(확인 페이지(/store))

헤더 외의 문제들 (아직 작업 안된 거 말씀 드리는 것 같아서 다음 작업 시 참고해주세요)
- 햄버거 메뉴 오픈 시 로그인 메뉴와 설정 메뉴가 너무 밑에 있습니다
- 메인 페이지(/)에서 인기 게임 같이 우측으로 길게 표시되는 경우 우측으로 스크롤이 돼 불편합니다
- 위의 이슈 때문인지 창 사이즈가 커져 로그인 모달이 정상적인 위치에서 표기되지 않습니다
- 스크롤 시 로그인 모달의 바탕 하단이 비어 있습니다

2023-08-20 15:12 UTC, Se0nAh commented
@DOS0313 모바일 기기로 확인을 안 해서 놓친 것 같네요 요 부분들 모바일 헤더 건으로 따로 진행해도 될까요?

2023-08-20 15:13 UTC, DOS0313 commented
편하신대로 진행해주세요~!

2023-08-21 08:30 UTC, markyul commented
이미지는 비율로 반응형을 하는군요 저도 다음엔 그렇게 해봐야겠어요!

2023-08-21 09:27 UTC, merged