Feature: game detail
WakGames/Waktaverse-Games pull request #280
Opened 2023-08-20 11:35 UTC by markyul

## 개요

- 게임 상세페이지 반응형, 정보 추가

## 작업 내용

- 반응형 추가
- 배치, 게임 추가 정보, 패치 노트 추가
- 태그 더보기

## 스크린샷(or 동영상)

## 기타(특이 사항)

- 어플 정보 페이지 곧 추가할게여

2023-08-21 06:01 UTC, DOS0313 commented
게임 상세정보 페이지 반응형 작업 완료 된걸까요?

2023-08-21 08:21 UTC, DOS0313 requested changes
추가 답변 없어 이슈 먼저 말씀드리겠습니다
- Tablet Size : 스크린샷 및 설명 등이 죄측 정렬됨
(중간 디자인이 생략되어 있긴 한데 혹시 게임 설명을 창 사이즈에 따라서 변동되게 할 수 있을까요? = 오른쪽 남은 구역까지 설명 표기)
- Tablet Size : 버튼 위치가 Figma와 다름
(Figma 상에서는 버튼이 스크린샷 위치와 같은 곳에 있는데 isol_dia로 확인한 결과 설명이 많지도 않은데 버튼 위치가 일치하지 않습니다)

- Mobile Size : 플레이 영상이 중앙 정렬 되어야 할 것 같습니다
- Mobile Size : 스크린샷/PV 및 설명 그리고 버튼 margin이 제대로 적용되지 않은 것 같습니다.

2023-08-21 11:23 UTC, markyul commented
@DOS0313 
위의 사항들 수정했습니다

2023-08-21 12:49 UTC, DOS0313 requested changes
수고하셨습니다. 근데 이슈가 꽤 있네요..ㅠㅠ
- Tablet / Mobile Size : 플레이 영상 누락됨
ex)5개 이상 있어도 4개만 표기됨
- Mobile Size : 게임 플레이 영상을 그냥 창 사이즈에 맞춰서 작업하는 것도 좋을 것 같습니다
![image](https://github.com/WakGames/Waktaverse-Games/assets/119480595/bf2bc6c1-08d1-4f9c-beae-c6ff91363efe)
(이렇게 될 경우 좌측 정렬로 돌아가야 할 것 같네요)

- isol_dia 패치노트가 이상합니다

2023-08-21 12:50 UTC, DOS0313 commented
isol_dia 패치노트는 확인했습니다

2023-08-23 09:42 UTC, DOS0313 commented
![Screenshot_20230823_184121_Chrome.jpg](https://github.com/WakGames/Waktaverse-Games/assets/119480595/a7460758-5676-4460-b094-cca79b9d6686)

모바일로 접속해서 확인해봤는데 플레이 영상부분은 패치된거 같은데 스크린샷이랑 PV 영상 표시부과 좌측으로 밀려있습니다

2023-08-23 12:26 UTC, DOS0313 commented
그리고 하나 누락했었네요;;
![image](https://github.com/WakGames/Waktaverse-Games/assets/119480595/9f94ab31-7b79-4cb9-969f-e0c43353bbe0)
디자인을 보시면 게임 플레이 영상 부분에 **자세히 보기**를 가르키는 버튼이 있어서 클릭 시 해당 게임 팬게임 영상 리스트로 이동되어야 합니다. (왁타버스 게임 플레이 영상 페이지에 검색어 사용하는 방법?)

2023-08-25 04:48 UTC, DOS0313 reviewed
영상 모음 페이지로 이동할 때 해당 게임의 영상만 영상 모음 페이지에서 보여지게 작업 해주실 수있나요?

(오래 걸릴 것으로 보이면 다른 브랜치에서 진행 해주셔도 됩니다)

2023-08-25 12:04 UTC, DOS0313 approved these changes

2023-08-25 12:04 UTC, merged