fix: (모바일) 화면 넘어가서 스크롤 되지 않도록 수정
WakGames/Waktaverse-Games pull request #284
Opened 2023-08-22 12:32 UTC by Se0nAh

## 개요

- (모바일) 화면 넘어가서 스크롤 되지 않도록 수정

## 작업 내용

- 게임 리스트로 인해 화면 밖으로 스크롤 되는 현상 수정
- 헤더가 안 보이거나 좌측 메뉴의 설정, 로그인 버튼이 하단 밑으로 내려가는 현상이 함께 고쳐집니다

## 스크린샷(or 동영상)
![image](https://github.com/WakGames/Waktaverse-Games/assets/49391145/61359531-3154-49e6-bc8c-6667c1f47ebe)
![image](https://github.com/WakGames/Waktaverse-Games/assets/49391145/eabdce0a-10a0-4171-a958-0103e3039e03)

## 기타(특이 사항)

- 비디오 카드의 제목이 길어지면 제한없이 가로로 커지는 현상이 있는데 이건 좀 더 봐야할 것 같습니다 ㅜ.ㅜ 
채널명이랑 제목이 한 줄에 있어서 징짱 채널처럼 채널명이 길면 제목이 조금만 보이는데 모바일에선 두줄로 각각 표시하는 게 어떨까요?

2023-08-22 13:07 UTC, DOS0313 requested changes
수고하셨습니다!
아래 부분 약간 수정해주시면 좋을 것 같습니다
- 메인 페이지 헤더가 조금만 스크롤 해도 바탕 색이 적용되면 좋을 것 같습니다.
(애니메이션이 들어가 있기도 하고 배너의 텍스트랑 겹쳐서 보여서)

2023-08-23 01:08 UTC, DOS0313 approved these changes
완벽하게 처리는 힘들 것 같네요. 수고하셨습니다!
혹시 모르니 @WakGames/frontend 팀 분들 확인 부탁드립니다

2023-08-23 01:12 UTC, Kim-EunKyu approved these changes
고생하셨습니다!!

2023-08-23 01:15 UTC, kms0219kms commented
무식하게 overflow-x: hidden; 으로는 해결이 안되던가요...?
징쨩 채널처럼 이름이 긴건 truncate화하면 되지 않을까...가 제 의견입니다만

학교라 폰으로 보고 있어서 코드를 놓친게 있을 수 있으니.. 이미 반영된거라면 말씀해 주세요 😆

2023-08-23 14:25 UTC, merged

2023-08-23 14:29 UTC, Se0nAh commented
@kms0219kms 
현재는 채널은 고정이고 제목은 overflow hidden 처리해서 truncate 되는 상태인데, 제목이 길어지면 truncate가 적용되면서도 야금야금 width 가 길어지네요 ㅠㅠ 원인 찾으면 다른 PR에서 해결해 보겠습니다
채널명까지 truncate 처리한다면 채널과 제목 둘 다 길 때 각각 어디까지 표시할 것인가를 명확히 정해야해서 차라리 두 줄이 되는 게 제목과 채널을 좀더 잘 표시할 수 있지 않을까 생각했어요! 의견 감사합니다