Feat/achieve edit
WakGames/Waktaverse-Games pull request #295
Opened 2023-08-24 20:37 UTC by turtle85917

## 개요

- 도전과제 수정

## 작업 내용

- 도전과제 추가
- 도전과제 삭제
- 도전과제 수정

## 스크린샷(or 동영상)
![image](https://github.com/WakGames/Waktaverse-Games/assets/61219276/eb48da9f-5ce4-4d4a-b43a-6b03a05444a6)
![image](https://github.com/WakGames/Waktaverse-Games/assets/61219276/db2dd1ac-0100-42c9-bfe8-e5ea848d4c11)
![image](https://github.com/WakGames/Waktaverse-Games/assets/61219276/54ce6412-0b3f-45d9-ab11-31c2480497a8)

## 기타(특이 사항)

- 뒤로가기 시, 사이트에서 나가겠냐는 얼럿이 안 뜸

2023-08-25 06:31 UTC, NeuroWhAI commented
프론트 수정사항은 `frontend` 브랜치를 베이스로 수정 및 feature 브랜치 만들어주세요.

2023-08-25 12:20 UTC, DOS0313 requested changes
CBT에 포함이 되는 페이지는 아니라 수정필요 이슈들 말씀드리겠습니다.

- 도전과제 추가/수정사항 저장 버튼 디자인 다름 (Desktop / Tablet)
![image](https://github.com/WakGames/Waktaverse-Games/assets/119480595/9ebe7beb-0547-4fa6-acdc-2cfc65297a09)
- 정렬 기준 다름 (Mobile)
![image](https://github.com/WakGames/Waktaverse-Games/assets/119480595/18e4db24-d5ab-4424-8f56-d6a21029c372)

2023-08-25 12:24 UTC, DOS0313 commented
그리고 충돌도 있는 것 같습니다 해결 부탁드립니다
![image](https://github.com/WakGames/Waktaverse-Games/assets/119480595/9d6ad508-7b1b-4c14-ac26-914cbc664d88)

2023-08-25 13:20 UTC, DOS0313 commented
버튼 여백만 수정해주시면 될 것 같습니다

2023-08-27 03:34 UTC, DOS0313 requested changes
동일 ID인 HAPPY_END로 기입 시 처리 실패 알럿 후 처리 성공 알럿이 뜹니다

그리고 알럿 문구 변경이 필요합니다
- 처리 실패 -> 수정사항 저장 중에 오류가 발생했습니다
- 완료! -> 수정사항이 성공적으로 저장되었습니다

2023-08-27 03:35 UTC, DOS0313 commented
추가적으로 ESLint 오류 발생합니다
![image](https://github.com/WakGames/Waktaverse-Games/assets/119480595/33952665-2d55-4755-a6f1-998a334dceed)

2023-08-27 04:35 UTC, turtle85917 commented
UnclickBtn과 ClickBtn 차이가 뭔가요?

2023-08-27 05:12 UTC, turtle85917 commented
@DOS0313 확인 부탁드립니다.

2023-08-27 06:30 UTC, DOS0313 approved these changes
수고하셨어요!

2023-08-27 06:31 UTC, merged