feat: 삭제된 도전과제
WakGames/Waktaverse-Games pull request #338
Opened 2023-08-30 12:24 UTC by turtle85917

## 개요

- 삭제된 도전과제 표기

## 작업 내용

- 삭제된 도전과제 표기

## 스크린샷(or 동영상)

## 기타(특이 사항)

- 없음

2023-08-30 12:31 UTC, DOS0313 approved these changes
수고하셨스빈다

2023-08-30 12:33 UTC, DOS0313 requested changes
모바일 반응형 작업 필요할 것 같습니다

(바로 Figma 올려드리겠습니다)

2023-08-31 11:31 UTC, DOS0313 commented
```
Compiled with warnings.

[eslint]
src\domain\intro\pages\DevPortal\Authorized\ConnectGame\GameDetail\GameAchieve.js
  Line 10:10:  'achieveListSize' is assigned a value but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint]
src\domain\intro\pages\DevPortal\Authorized\ConnectGame\GameDetail\GameAchieve.js
  Line 10:10:  'achieveListSize' is assigned a value but never used  no-unused-vars

webpack compiled with 1 warning
```
ESLint 경고 있습니다

2023-08-31 11:32 UTC, turtle85917 commented
achieveListSize를 삭제할까요?

2023-08-31 11:37 UTC, DOS0313 approved these changes

2023-08-31 11:37 UTC, merged