Fix: library 관련
WakGames/Waktaverse-Games pull request #376
Opened 2023-09-09 14:58 UTC by markyul

## 개요

- library 페이지 관련 이슈과 자잘한 거

## 작업 내용

- 드롭다운 옵션이 페이지 이동시 초기화됌 https://discord.com/channels/1060178603758862346/1146472874392170677
- (모바일)페이지 이동시 열어놨던 위치와 동일한 위치의 UI가 펼쳐진 그대로 https://discord.com/channels/1060178603758862346/1146462303999508562
- 라이브러리 등록할때 취소 버튼 누르면 잘 안먹히는 버그(엣지) -> 삭제로 해결 https://discord.com/channels/1060178603758862346/1145005445484912640
- 앱, 게임이 따로 나열되서 나옴 -> 처음에 정렬이 안되던 문제 https://discord.com/channels/1060178603758862346/1144825536535867482
- 페이지네이션 클릭 범위 https://discord.com/channels/1060178603758862346/1144821339220357172

## 스크린샷(or 동영상)

## 기타(특이 사항)

- 없음

2023-09-10 00:58 UTC, DOS0313 reviewed
> 앱, 게임이 따로 나열되서 나옴 -> 처음에 정렬이 안되던 문제

이 부분은 그냥 어플과 게임을 라이브러리 상에서도 분리하는게 어떨까요?
(/store 페이지 처럼)

2023-09-14 13:02 UTC, DOS0313 approved these changes
수고하셨어요!

2023-09-14 13:08 UTC, kms0219kms requested changes
Conflict 해결되기만 하면 좋을거 같스무니다

2023-09-14 13:16 UTC, Kim-EunKyu approved these changes
고생하셨습니다!

2023-09-14 13:20 UTC, merged