프로필 페이지 전반적인 반응형 디자인, 기능 수정
WakGames/Waktaverse-Games pull request #420
Opened 2023-09-24 13:20 UTC by Kim-EunKyu

## 개요

- 프로필 페이지 전반적인 반응형 디자인, 기능 수정

## 작업 내용

- 피그마 디자인 참고하여 전부 최대한 반응형 디자인 적용하였습니다.
- 데이터가 없거나 로딩중일때에 문구 추가하였습니다.
- 반응형이다보니 팬덤, 그룹, 도전과제, 나의 게임 등등 데이터가 있고 없을때 한번 세심하게 봐주시면 정말 감사하겠습니다 ㅎㅎ 이상한 부분 있으면 피드백 말씀 부탁드립니다.

## 스크린샷(or 동영상)

데스크톱
![image](https://github.com/WakGames/Waktaverse-Games/assets/59270535/76cc7afb-d23e-4f92-b92c-cc90ed5db312)

태블릿
![image](https://github.com/WakGames/Waktaverse-Games/assets/59270535/870741d8-fd90-45ce-b66d-907c53b2fce0)

모바일
![image](https://github.com/WakGames/Waktaverse-Games/assets/59270535/4a2a0094-c390-4b6c-98eb-b1f788961898)

## 기타(특이 사항)

- 저도 작업한지 좀 되었다보니 커밋을 이상하게 두개나 커밋한..; 이런 경우를 많이 겪어보지 못해서 수정할 수 있는 방법 있는지 한번 찾아보겠습니다 ㅎ..

2023-09-24 13:26 UTC, DOS0313 requested changes
![image](https://github.com/WakGames/Waktaverse-Games/assets/119480595/8599347b-fdf7-49a4-980a-85f0d3fceda6)
해당 부분도 같이 진행 해주실 수 있나요?

(로그인 부분은 로그인 이후에 프로필로 표기되야 합니다)

2023-09-24 13:44 UTC, DOS0313 requested changes
도전과제 보는 부분 좌우 이동 버튼 클릭 시 가운데 도전과제를 스킵합니다
![Animation6](https://github.com/WakGames/Waktaverse-Games/assets/119480595/d4d657fa-66c9-49dc-a7ce-64431b366e67)

2023-09-24 13:50 UTC, Kim-EunKyu commented
@DOS0313 
첫번째 말씀주신거가 저번에 이어서 하려던 부분이었네요! 마저 처리하겠습니다.
두번째 도전과제는.. 라이브러리 사용법을 계속 봤는데도 조금 어렵네요 ㅎ... 한번 개선해볼 수 있는 방법을 계속 찾아보겠습니다. 우선 현재는 드래그로 천천히 볼수는 있습니다만 좌우 버튼 제어가 지금은 한번에 가는지라..어쨌든 찾아보겠습니다!!

2023-09-30 09:36 UTC, DOS0313 approved these changes
작동 상에 큰 문제는 없는 것 같습니다!

수고 많으셨어요!

2023-09-30 11:11 UTC, kms0219kms approved these changes
LGTM

2023-09-30 14:08 UTC, merged