프로필 페이지 리워크 적용
WakGames/Waktaverse-Games pull request #98
Opened 2023-03-31 13:03 UTC by Kim-EunKyu

## 개요

- 프로필 페이지 리워크 디자인 적용했습니다.

## 작업 내용

- 커밋된 파일이 많습니다만, 반절이 테스트용 svg라서 제일 중요한 파일은 profile폴더에 있는 index.js를 봐주시면 될 것 같습니다.
- 우선 전체적으로 피그마에 디자인되어있는 것을 따라서 리워크 진행하였습니다.
- 도전과제는 swiper라이브러리 사용하였고 하단에 그래프는 chart.js를 사용했습니다.
- 디자인 적으로 이상한 부분이 없는지 한번 확인 부탁드립니다 ㅎㅎ

## 스크린샷(or 동영상)

https://user-images.githubusercontent.com/59270535/229127238-79b637eb-7660-479d-95d6-f996ba9bc675.mp4

## 기타(특이 사항)

- api연동까지 하면 사이즈가 너무 커질것같아서 우선 디자인만 적용하고 api연동은 요 작업 이후에 진행하겠습니다.
- 도전과제도 원래 마우스를 대면 설명이 떠야하는데 이부분도 api 불러오고 작업이 들어갈 것 같습니다.

2023-03-31 15:32 UTC, DOS0313 requested changes
작업 너무 수고하셨고요!
간단한 수정 사항들 있는거 같습니다
- 최근에 다운로드한 게임 폰트 사이즈가 디자인과 차이가 있습니다 (디자인 : 18px / 사이트 : 16px)
- 그룹 옆에 여백이 스크롤 바를 생각하지 않고 구현되어 있는거 같습니다
(스크롤 바 사이즈만큼 더 잘라 주셔야 할 듯 합니다)
- 가능하다면 차트 두께(?)를 늘릴 수 있을까요?
(디자인 상에서는 60px 입니다)

추가적으로 확인되면 코멘트 남기겠습니다

2023-04-01 11:09 UTC, markyul reviewed
아직 UI만 한거니까 많이 말할게 없네요!
그리고 한 파일에 코드가 너무 길어지면 파일을 나누는거도 좋은 방법이에요 ㅎㅎ

2023-04-01 11:09 UTC, markyul commented on frontend/src/pages/Profile/index.js
> +import { useEffect } from 'react';
```suggestion
import { useState, useEffect } from 'react';
```
이렇게 한줄에 넣을 수 있고
다른 import는 비슷한 애들끼리 순서대로 나열하면 찾기 편할 것 같아요

2023-04-01 11:15 UTC, DOS0313 approved these changes
일단 지금봤을때는 디자인 상으로는 큰 문제 없는거 같네요!
수고하셨습니다~ 킹아!

2023-04-15 05:10 UTC, merged